[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo =  'w0ng/vim-hybrid'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'
on_i = 1

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

#[[plugins]]
#repo = 'elixir-lang/vim-elixir'
#on_ft = ['elixir', 'eelixir']

[[plugins]]
repo = 'slashmili/alchemist.vim'
on_ft = ['elixir', 'eelixir']

[[plugins]]
repo = 'elixir-editors/vim-elixir'
